# [terminal.shell]
# program = "/usr/local/bin/zsh"
# args = ["-1"]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
startup_mode = "Maximized"
blur = true
option_as_alt = "OnlyLeft"
opacity = 1

[general]
live_config_reload = true
import = ["~/.config/alacritty/tokyonight_moon.toml"]

[scrolling]
history = 100000

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
bold = { family = "Maple Mono NF CN", style = "Bold" }
italic = { family = "Maple Mono NF CN", style = "Italic" }
bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }
size = 15

[bell]
animation = "EaseOutExpo"
duration = 100
color = "#ffffff"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true
