
backtraces_path = "~/.config/neovide/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
neovim-bin = "/usr/local/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["Maple Mono NF CN"]
size = 13.0
