abbr -a v "nvim"
abbr -a f "fuck"
abbr -a ls "eza --icons"
abbr -a ll "eza -lg --icons"
abbr -a cat "bat"
abbr -a tn "tmux new -s"
abbr -a ta "tmux a -t"
abbr -a y "yazi"
abbr -a lg "lazygit"
abbr -a pdm_shell "eval (pdm venv activate in-project)"
abbr -a pyactivate "source .venv/bin/activate.fish"
