abbr -a v "nvim"
# abbr -a f "fuck"
abbr -a ls "eza --icons"
abbr -a lsg "eza --icons --git-ignore"
abbr -a lls "eza -lg --icons --total-size"
abbr -a ll "eza -lg --icons"
abbr -a llgs "eza -lg --icons --total-size --git-ignore"
abbr -a llg "eza -lg --icons --git-ignore"
abbr -a cat "bat"
abbr -a grep "rg"
abbr -a tn "tmux new -s"
abbr -a ta "tmux a -t"
abbr -a y "yazi"
abbr -a lg "lazygit"
abbr -a pdm_shell "eval (pdm venv activate in-project)"
abbr -a pyactivate "source .venv/bin/activate.fish"
