abbr -a v "nvim"
abbr -a vi "nvim"
abbr -a vim "nvim"
# abbr -a f "fuck"
abbr -a cd "z"
abbr -a j "z"
abbr -a ls --set-cursor "eza % --icons"
abbr -a lsg --set-cursor "eza % --icons --git-ignore"
abbr -a lls --set-cursor "eza % -lg --icons --total-size"
abbr -a ll --set-cursor "eza % -lg --icons"
abbr -a llgs --set-cursor "eza % -lg --icons --total-size --git-ignore"
abbr -a llg --set-cursor "eza % -lg --icons --git-ignore"
abbr -a grep "rg"
abbr -a tn "tmux new -s"
abbr -a ta "tmux a -t"
abbr -a y "yazi"
abbr -a lg "lazygit"
abbr -a pyactivate "source .venv/bin/activate.fish"
abbr -a fzf "sk"
