set -gx PATH /Users/jason/.local/share/zinit/polaris/bin $PATH
set -gx PATH /Users/jason/bin $PATH
set -gx PATH /usr/local/bin $PATH
set -gx PATH /Library/TeX/texbin $PATH
set -gx PATH /usr/local/Cellar/mupdf/1.25.4/bin $PATH
set -gx PATH /opt/local/bin $PATH
set -gx PATH /opt/local/sbin $PATH
set -gx PATH /Users/jason/.local/bin $PATH
set -gx PATH /Applications/ltex-ls-16.0.0/bin $PATH
set -gx PATH /usr/local/bin $PATH
set -gx PATH /usr/bin $PATH
set -gx PATH /bin $PATH
set -gx PATH /usr/sbin $PATH
set -gx PATH /sbin $PATH
set -gx PATH /Library/TeX/texbin $PATH
set -gx PATH /Users/jason/.local/bin $PATH
set -gx PATH /Users/jason/.local/share/zinit/plugins/unixorn---fzf-zsh-plugin/bin $PATH
set -gx PATH /Users/jason/.fzf/bin $PATH
