local add, now, later = MiniDeps.add, MiniDeps.now, MiniDeps.later
add({ source = "OXY2DEV/markview.nvim" })
add({ source = "lervag/vimtex" })
add({ source = "ethanholz/nvim-lastplace" })
add({ source = "christoomey/vim-tmux-navigator" })
add({ source = "dstein64/vim-startuptime" })
add({ source = "LunarVim/bigfile.nvim" })
now(function()
  require("plugins.utils.files")
  require("mini.pairs").setup()
  require("mini.sessions").setup({})
  require("nvim-lastplace").setup()
end)
later(function()
  require("plugins.utils.pick")
  require("plugins.utils.jump")
  require("plugins.utils.markview")
  require("plugins.utils.vimtex")
  require("mini.align").setup()
  require("mini.ai").setup()
  require("mini.surround").setup()
  vim.keymap.set({ "n", "x" }, "s", "<Nop>")
  require("mini.extra").setup()
  require("mini.move").setup()
end)
